import { Preferences } from '@capacitor/preferences';
import { isNative } from './platform';

// Stable per-install device identifier. Keyed on the original filesystem
// storage (Capacitor Preferences on native, localStorage on web) so it
// survives token rotations but NOT app reinstalls or browser storage
// clears — which is what we want: a wiped device looks like a new device.
//
// Written on first call, reused thereafter. Generated by crypto.randomUUID()
// (no Capacitor Device plugin dependency, same UUID format across platforms).

const KEY = 'sessio_device_id';

let cachedId: string | null = null;

export async function getDeviceId(): Promise<string> {
  if (cachedId) return cachedId;

  if (isNative) {
    const { value } = await Preferences.get({ key: KEY });
    if (value) {
      cachedId = value;
      return value;
    }
    const fresh = crypto.randomUUID();
    await Preferences.set({ key: KEY, value: fresh });
    cachedId = fresh;
    return fresh;
  }

  // Web — localStorage
  let id = localStorage.getItem(KEY);
  if (!id) {
    id = crypto.randomUUID();
    localStorage.setItem(KEY, id);
  }
  cachedId = id;
  return id;
}
