// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isNative } from '@/lib/platform';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Capacitor (iOS/Android): single-WebView, no multi-tab contention.
    // The default Web Locks–based lock causes "lock was released because
    // another request stole it" errors on iOS WKWebView. A no-op lock is
    // safe in single-WebView apps. Web browsers need the real lock to
    // serialize concurrent token refreshes and avoid session corruption.
    ...(isNative ? { lock: (name: string, acquireTimeout: number, fn: () => Promise<any>) => fn() } : {}),
  }
});